/**
 * FileService — all native file I/O behind user-driven save dialogs.
 *
 * Security notes (CANON §16):
 *   - file names coming from the renderer are sanitized (basename only, control
 *     characters and separators stripped, length capped) before touching a path;
 *   - only paths the user explicitly picked in a save dialog are ever returned
 *     to the renderer; temp files used for printing are never exposed.
 */
import { app, BrowserWindow, dialog, shell } from 'electron';
import { randomBytes } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { ExportFileResponse, PrintPdfResponse, SavePdfResponse } from '../ipc/channels';

const MAX_FILE_NAME_LENGTH = 200;

/** Extension → save-dialog filter mapping for generic exports. */
const EXPORT_FILTERS: Readonly<Record<string, { name: string; extensions: string[] }>> = {
  pdf: { name: 'PDF', extensions: ['pdf'] },
  csv: { name: 'CSV', extensions: ['csv'] },
  json: { name: 'JSON', extensions: ['json'] },
  png: { name: 'PNG image', extensions: ['png'] },
  jpg: { name: 'JPEG image', extensions: ['jpg', 'jpeg'] },
  txt: { name: 'Text', extensions: ['txt'] },
};

/** Strips path components / illegal characters; returns null when nothing safe remains. */
export function sanitizeFileName(input: string): string | null {
  const base = path
    .basename(input)
    .replace(/[\\/:*?"<>|\u0000-\u001F]/g, '')
    .trim();
  if (base.length === 0 || base.length > MAX_FILE_NAME_LENGTH) return null;
  return base;
}

function toErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : 'Unknown filesystem error.';
}

/** Writes the buffer, creating the target directory when missing. */
async function writeOut(filePath: string, data: ArrayBuffer): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, Buffer.from(data));
}

export const FileService = {
  /**
   * Saves a PDF behind a native save dialog (defaults to the user's Documents
   * folder). Resolves `{ ok: false, cancelled: true }` when the user cancels.
   */
  async savePdf(data: ArrayBuffer, fileName: string, parentWindow?: BrowserWindow): Promise<SavePdfResponse> {
    const safeName = sanitizeFileName(fileName);
    if (safeName === null) return { ok: false, error: 'Invalid file name.' };
    const suggested = safeName.toLowerCase().endsWith('.pdf') ? safeName : `${safeName}.pdf`;

    const options = {
      title: 'Save PDF',
      defaultPath: path.join(app.getPath('documents'), suggested),
      filters: [{ name: 'PDF', extensions: ['pdf'] }],
    };
    const result = parentWindow
      ? await dialog.showSaveDialog(parentWindow, options)
      : await dialog.showSaveDialog(options);

    if (result.canceled || result.filePath === undefined) return { ok: false, cancelled: true };
    try {
      await writeOut(result.filePath, data);
      return { ok: true, path: result.filePath }; // user-chosen path — allowed to surface
    } catch (error) {
      return { ok: false, error: toErrorMessage(error) };
    }
  },

  /**
   * Writes a PDF to a random file in the OS temp directory (printing helper).
   * The path stays internal — it is never sent to the renderer.
   */
  async writeTempPdf(data: ArrayBuffer): Promise<string> {
    const tempDir = app.getPath('temp');
    await mkdir(tempDir, { recursive: true }); // ensure the dir exists
    const filePath = path.join(
      tempDir,
      `invoiceflow-${Date.now().toString(36)}-${randomBytes(8).toString('hex')}.pdf`,
    );
    await writeFile(filePath, Buffer.from(data));
    return filePath;
  },

  /**
   * Prints a PDF generated by the renderer.
   *
   * Trade-off (documented): `webContents.printToPDF` renders HTML → PDF; it cannot
   * re-print an existing PDF blob, and loading a PDF into a BrowserWindow depends
   * on Chromium's PDF viewer extension, which exposes no programmatic printing.
   * The robust cross-platform approach is therefore: temp file → OS default PDF
   * application (Preview / Acrobat / Edge), which shows the native print dialog.
   * Future (CANON Phase 8): native print spooling (CUPS / Win32 Print API).
   */
  async printPdf(data: ArrayBuffer, _parentWindow?: BrowserWindow): Promise<PrintPdfResponse> {
    try {
      const tempPath = await FileService.writeTempPdf(data);
      const openError = await shell.openPath(tempPath); // '' on success
      if (openError.length > 0) return { ok: false, error: openError };
      return { ok: true };
    } catch (error) {
      return { ok: false, error: toErrorMessage(error) };
    }
  },

  /**
   * Generic export (CSV/JSON/…) behind a native save dialog. The extension of
   * the suggested name drives the dialog filter. `_contentType` is reserved for
   * future metadata stamping.
   */
  async exportFile(
    data: ArrayBuffer,
    fileName: string,
    _contentType: string | undefined,
    parentWindow?: BrowserWindow,
  ): Promise<ExportFileResponse> {
    const safeName = sanitizeFileName(fileName);
    if (safeName === null) return { ok: false, error: 'Invalid file name.' };
    const ext = path.extname(safeName).replace(/^\./, '').toLowerCase();
    const filter = EXPORT_FILTERS[ext];

    const options = {
      title: 'Export file',
      defaultPath: path.join(app.getPath('documents'), safeName),
      filters: filter ? [filter, { name: 'All files', extensions: ['*'] }] : undefined,
    };
    const result = parentWindow
      ? await dialog.showSaveDialog(parentWindow, options)
      : await dialog.showSaveDialog(options);

    if (result.canceled || result.filePath === undefined) return { ok: false, cancelled: true };
    try {
      await writeOut(result.filePath, data);
      return { ok: true, path: result.filePath };
    } catch (error) {
      return { ok: false, error: toErrorMessage(error) };
    }
  },
};
